- name: Copy service-account private key pair 
  ansible.builtin.copy:
    src: "../../shared/files/ssl{{ kube_ssl_base_path }}/{{ item }}"
    dest: "{{ kube_ssl_base_path }}/{{ item }}"
  with_items:
    - sa.key
    - sa.pub 
  tags:
    - distribute-certs
