- name: Distribute etcd binary
  ansible.builtin.copy:
    src: "../../shared/files/binaries/etcd-{{ etcd_version }}"
    dest: "/usr/local/bin/etcd-{{ etcd_version }}"
    owner: root
    group: root
    mode: 0755 
  tags:
  - distribute-bins
  - disribute-etcd-bin

- name: Link etcd binary  
  ansible.builtin.file:
    src: "etcd-{{ etcd_version }}"
    dest: "/usr/local/bin/etcd"
    mode: "0777"
    owner: root
    group: root
    state: link
  tags:
  - distribute-bins
  - disribute-etcd-bin

- name: Distribute etcdctl binary
  ansible.builtin.copy:
    src: "../../shared/files/binaries/etcdctl-{{ etcdtool_version }}"
    dest: "/usr/local/bin/etcdctl-{{ etcdtool_version }}"
    owner: root
    group: root
    mode: 0755 
  tags:
  - distribute-bins
  - disribute-etcd-bin

- name: Link etcdctl binary  
  ansible.builtin.file:
    src: "etcdctl-{{ etcdtool_version }}"
    dest: "/usr/local/bin/etcdctl"
    mode: "0777"
    owner: root
    group: root
    state: link
  tags:
  - distribute-bins
  - disribute-etcd-bin
