- name: Copy node cert pems
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/node-{{ item }}.pem"
    dest: "{{ playbook_dir }}/shared/files/ssl/etc/kubernetes/pki/node-{{ item }}.crt"
    owner: root
    group: root
    mode: 0640
  with_items: 
    - "{{ groups['worker_hosts'] }}"
    - "{{ groups['master_hosts'] }}"
  tags:
    - rename-pems
    - generate-node-pems

- name: Copy node key pems
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/node-{{ item }}-key.pem"
    dest: "{{ playbook_dir }}/shared/files/ssl/etc/kubernetes/pki/node-{{ item }}.key"
    owner: root
    group: root
    mode: 0640
  with_items: 
    - "{{ groups['worker_hosts'] }}"
    - "{{ groups['master_hosts'] }}"
  tags:
    - rename-pems
    - generate-node-pems

- name: Copy node pems csr
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/node-{{ item }}.csr"
    dest: "{{ playbook_dir }}/shared/files/ssl/csr/node-{{ item }}.csr"
    owner: root
    group: root
    mode: 0640
  with_items: 
    - "{{ groups['worker_hosts'] }}"
    - "{{ groups['master_hosts'] }}"
  tags:
    - rename-pems
    - generate-node-pems

- name: Delete old node pems
  ansible.builtin.file:
    path: "{{ playbook_dir }}/shared/files/ssl/node-{{ item }}.csr"
    state: absent
  with_items: 
    - "{{ groups['worker_hosts'] }}"
    - "{{ groups['master_hosts'] }}"
  when: ssl_cleanup_after_generation 
  tags:
    - rename-pems
    - generate-node-pems
