- name: Copy worker node cert pems
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/worker-node-{{ item }}.pem"
    dest: "{{ playbook_dir }}/shared/files/ssl/etc/kubernetes/pki/worker-node-{{ item }}.crt"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ groups['worker_hosts'] }}"

- name: Copy worker-node key pems
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/worker-node-{{ item }}-key.pem"
    dest: "{{ playbook_dir }}/shared/files/ssl/etc/kubernetes/pki/worker-node-{{ item }}.key"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ groups['worker_hosts'] }}"

- name: Copy worker-node pems csr
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/worker-node-{{ item }}.csr"
    dest: "{{ playbook_dir }}/shared/files/ssl/csr/worker-node-{{ item }}.csr"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ groups['worker_hosts'] }}"

- name: Delete old worker node pems
  ansible.builtin.file:
    path: "{{ playbook_dir }}/shared/files/ssl/worker-node-{{ item }}.csr"
    state: absent
  with_items: "{{ groups['worker_hosts'] }}"
  when: ssl_cleanup_after_generation 
