- name: Copy worker node cert pems
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/master-node-{{ item }}.pem"
    dest: "{{ playbook_dir }}/shared/files/ssl/etc/kubernetes/pki/master-node-{{ item }}.crt"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ groups['master_hosts'] }}"

- name: Copy master node key pems
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/master-node-{{ item }}-key.pem"
    dest: "{{ playbook_dir }}/shared/files/ssl/etc/kubernetes/pki/master-node-{{ item }}.key"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ groups['master_hosts'] }}"

- name: Copy master node pems csr
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/files/ssl/master-node-{{ item }}.csr"
    dest: "{{ playbook_dir }}/shared/files/ssl/csr/master-node-{{ item }}.csr"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ groups['master_hosts'] }}"

- name: Delete old master node pems
  ansible.builtin.file:
    path: "{{ playbook_dir }}/shared/files/ssl/master-node-{{ item }}.csr"
    state: absent
  with_items: "{{ groups['master_hosts'] }}"
  when: ssl_cleanup_after_generation 
