- name: Create /etc/cni/net.d directory
  ansible.builtin.file:
    path: /etc/cni/net.d
    owner: root
    group: root
    mode: '0750'
    state: directory

- name: Create /etc/containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    owner: root
    group: root
    mode: '0750'
    state: directory

- name: Create /var/lib/kubelet/pki directory
  ansible.builtin.file:
    path: /var/lib/kubelet/pki
    owner: root
    group: root
    mode: '0750'
    state: directory
    recurse: yes

- name: Create /etc/kubernetes/pki directory
  ansible.builtin.file:
    path: /etc/kubernetes/pki
    owner: root
    group: root
    mode: '0750'
    state: directory
    recurse: yes

- name: Create /opt/images container tar directory
  ansible.builtin.file:
    path: /opt/images
    owner: root
    group: root
    mode: '0750'
    state: directory
    recurse: yes
  tags:
    - distribute-images

- name: Create /opt/cni/bin directory for kubelet
  ansible.builtin.file:
    path: /opt/cni/bin
    owner: root
    group: root
    mode: '0750'
    state: directory
    recurse: yes

- name: Link cni bins to /opt/cni/bin
  ansible.builtin.file:
    src: "/usr/local/bin/cni-plugins-{{ cni_version }}"
    dest: "/opt/cni/bin"
    mode: "0777"
    owner: root
    group: root
    state: link
