

- name: Distribute container images to start base services
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/images/{{ item }}.tar"
    dest: "/opt/images/{{ item }}.tar"
  with_items: 
    - "coredns-{{ images.coredns_version }}"
    - "cpa-{{ images.cpa_version }}"
    - "jessie-dnsutils-{{ images.jessie_dnsutils_version }}"
    - "pause-{{ images.pause_version }}"
    - "tigera-operator-{{ images.tigera_operator_version }}"
  tags:
    - distribute-images
  

- name: Load image to containerd, namespace k8s.io
  ansible.builtin.command:
    argv: 
      - /usr/local/bin/ctr
      - -n 
      - k8s.io
      - image
      - import 
      - "/opt/images/{{ item }}.tar"
  with_items: 
    - "coredns-{{ images.coredns_version }}"
    - "cpa-{{ images.cpa_version }}"
    - "jessie-dnsutils-{{ images.jessie_dnsutils_version }}"
    - "pause-{{ images.pause_version }}"
    - "tigera-operator-{{ images.tigera_operator_version }}"
  tags:
    - distribute-images