- name: Template bridge netowork config
  ansible.builtin.template:
    src: etc/net.d/10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf
    owner: root
    group: root
    mode: 0644
  
- name: Template loopback network config
  ansible.builtin.template:
    src: etc/net.d/99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
    owner: root
    group: root
    mode: 0644
  