- name: Copy containerd config
  ansible.builtin.copy:
    src: etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  
- name: Template kubelet config
  ansible.builtin.template:
    src: etc/kubelet-config.yaml.j2
    dest: /var/lib/kubelet/config.yaml
    owner: root
    group: root
    mode: 0644

- name: Template kubelet config
  ansible.builtin.template:
    src: etc/kube-proxy.yaml.j2
    dest: /var/lib/kubelet/kube-proxy-config.yaml
    owner: root
    group: root
    mode: 0644