

- name: Distribute container images to start base services
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/images/{{ item }}.tar"
    dest: "/opt/images/{{ item }}.tar"
  with_items: 
    - "calico_cni-{{ images.calico_cni_version }}"
    - "calico_csi-{{ images.calico_csi_version }}"
    - "calico_node_driver_registrar-{{ images.calico_node_driver_registrar_version }}"
    - "calico_node-{{ images.calico_node_version }}"
    - "calico_pod2daemon_flexvol-{{ images.calico_pod2daemon_flexvol }}"
    - "calico_typha-{{ images.calico_typha_version }}"
    - "coredns_coredns-{{ images.coredns_version }}"
    - "cpa-{{ images.cpa_version }}"
    - "jessie-dnsutils-{{ images.jessie_dnsutils_version }}"
    - "pause-{{ images.pause_version }}"
    - "tigera-operator-{{ images.tigera_operator_version }}"
    - "calico_kube_controllers-{{ images.calico_kube_controllers_version }}"
    - "calico_apiserver-{{ calico_apiserver_version }}"
  tags:
    - distribute-images
  

- name: Load image to containerd, namespace k8s.io
  ansible.builtin.command:
    argv: 
      - /usr/local/bin/ctr
      - -n 
      - k8s.io
      - image
      - import 
      - "/opt/images/{{ item }}.tar"
  with_items: 
    - "calico_cni-{{ images.calico_cni_version }}"
    - "calico_csi-{{ images.calico_csi_version }}"
    - "calico_node_driver_registrar-{{ images.calico_node_driver_registrar_version }}"
    - "calico_node-{{ images.calico_node_version }}"
    - "calico_pod2daemon_flexvol-{{ images.calico_pod2daemon_flexvol }}"
    - "calico_typha-{{ images.calico_typha_version }}"
    - "coredns_coredns-{{ images.coredns_version }}"
    - "cpa-{{ images.cpa_version }}"
    - "jessie-dnsutils-{{ images.jessie_dnsutils_version }}"
    - "pause-{{ images.pause_version }}"
    - "tigera-operator-{{ images.tigera_operator_version }}"
    - "calico_kube_controllers-{{ images.calico_kube_controllers_version }}"
    - "calico_apiserver-{{ calico_apiserver_version }}"
  tags:
    - distribute-images