- name: Generate config for kube-proxy from kubectl
  ansible.builtin.command:
    argv: 
      - /usr/local/bin/kubectl 
      - config 
      - set-cluster 
      - "{{ kube_name }}"
      - "--certificate-authority={{ kube_ssl_base_path }}/ca.crt"
      - --embed-certs=true
      - "--server=https://{{ kube_api_addr }}:6443"
      - --kubeconfig=/var/lib/kubelet/kube-proxy.kubeconfig
  tags:
    - configure-worker
    - make-kube-proxy-conf

- name: Generate cred for kube-proxy from kubectl
  ansible.builtin.command:
    argv: 
      - /usr/local/bin/kubectl 
      - config 
      - set-credentials 
      - system:kube-proxy 
      - --client-certificate=/var/lib/kubelet/pki/kube-proxy.crt 
      - --client-key=/var/lib/kubelet/pki/kube-proxy.key
      - --embed-certs=true
      - --kubeconfig=/var/lib/kubelet/kube-proxy.kubeconfig
  tags:
    - configure-worker
    - make-kube-proxy-conf
   

- name: Link user cred with kube-proxy from kubectl
  ansible.builtin.command:
    argv: 
      - /usr/local/bin/kubectl 
      - config 
      - set-context 
      - default 
      - "--cluster={{ kube_name }}"
      - --user=system:kube-proxy
      - --kubeconfig=/var/lib/kubelet/kube-proxy.kubeconfig
  tags:
    - configure-worker
    - make-kube-proxy-conf
   
- name: Set linked context user cred with kube-proxy from kubectl
  ansible.builtin.command:
    argv: 
      - /usr/local/bin/kubectl 
      - config 
      - use-context 
      - default 
      - --kubeconfig=/var/lib/kubelet/kube-proxy.kubeconfig
  tags:
    - configure-worker
    - make-kube-proxy-conf
 
