- name: Create /etc/kubernetes/config directory
  ansible.builtin.file:
    path: /etc/kubernetes/config
    owner: root
    group: root
    mode: '0750'
    state: directory
  tags:
    - configure-master
    - install-master-services

