- name: Create tmp helm directory /tmp/helm
  ansible.builtin.file:
    path: /tmp/helm
    owner: root
    group: root
    mode: '0750'
    state: directory
  tags: 
    - disribute-helm-charts
    - deploy-helm-charts

- name: Distribute helm binary
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/shared/helm/"
    dest: "/tmp/helm/"
    owner: root
    group: root
    mode: 0755
  tags:
    - disribute-helm-charts
    - deploy-helm-charts

- name: Deploy helm charts
  ansible.builtin.command: 
    argv: 
      - /usr/local/bin/helm 
      - upgrade
      - --install
      - -n 
      - "{{ item.namespace }}"
      - "{{ item.chart }}"
      - "/tmp/helm/charts/{{ item.chart }}"
      - -f
      - "/tmp/helm/charts/{{ item.chart }}/values.yaml"
      - --create-namespace
      - --kubeconfig 
      - "{{ kube_etc_base_path }}/admin.conf"
  with_items:
    - chart: coredns
      namespace: coredns
  tags:
    - deploy-helm-charts

- name: Remove tmp directory /tmp/helm
  ansible.builtin.file:
    path: /tmp/helm/
    owner: root
    group: root
    mode: '0750'
    state: absent
  tags: 
    - disribute-helm-charts
    - deploy-helm-charts