- name: Distribute kubectl binary
  ansible.builtin.copy:
    src: "../../shared/files/binaries/{{ item }}-{{ kubernetes_version }}"
    dest: "/usr/local/bin/{{ item }}-{{ kubernetes_version }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - kubectl
    - kubeadm
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  tags:
    - distribute-bins
    - disribute-kube-bins

- name: Link kubectl binary  
  ansible.builtin.file:
    src: "{{ item }}-{{ kubernetes_version }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0777"
    owner: root
    group: root
    state: link
  with_items:
    - kubectl
    - kubeadm
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  tags:
    - distribute-bins
    - disribute-kube-bins

