- name: Generate config for kube-scheduler from kubectl
  ansible.builtin.command:
    argv: 
      - kubectl 
      - config 
      - set-cluster 
      - "{{ kube_name }}"
      - "--certificate-authority={{ kube_ssl_base_path }}/ca.crt"
      - --embed-certs=true
      - --server=https://127.0.0.1:6443
      - "--kubeconfig={{ kube_etc_base_path }}/scheduler.conf"


- name: Generate cred for kube-scheduler from kubectl
  ansible.builtin.command:
    argv: 
      - kubectl 
      - config 
      - set-credentials 
      - system:kube-scheduler
      - --client-certificate={{ kube_ssl_base_path }}/kube-scheduler.crt 
      - --client-key={{ kube_ssl_base_path }}/kube-scheduler.key
      - --embed-certs=true
      - "--kubeconfig={{ kube_etc_base_path }}/scheduler.conf"
 

- name: Link user cred with kube-scheduler from kubectl
  ansible.builtin.command:
    argv: 
      - kubectl 
      - config 
      - set-context 
      - default 
      - "--cluster={{ kube_name }}"
      - --user=system:kube-scheduler
      - "--kubeconfig={{ kube_etc_base_path }}/scheduler.conf"


- name: Set linked context user cred with kube-scheduler from kubectl
  ansible.builtin.command:
    argv: 
      - kubectl 
      - config 
      - use-context 
      - default 
      - "--kubeconfig={{ kube_etc_base_path }}/scheduler.conf"

