- name: Wait until controlplain is started
  ansible.builtin.command: 
    argv: 
      - /usr/local/bin/kubectl 
      - cluster-info
      - --kubeconfig 
      - "{{ kube_etc_base_path }}/admin.conf"
  register: controlplane_res
  retries: 5
  delay: 5
  until: "'is running at' in controlplane_res.stdout" 
  tags:
    - install-master-services
    - wait-controlplane

- name: Dump controlplain status
  ansible.builtin.debug:
    var: controlplane_res.stdout_lines
  tags:
    - install-master-services
    - wait-controlplane