[plugins]
  [plugins.cri.containerd]
    snapshotter = "overlayfs"
    [plugins.cri.containerd.default_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "/usr/local/bin/runc"
      runtime_root = ""
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."my-registry:5000"]
    endpoint = ["http://uaisbu-git3010p.portals.mos.local:5050"]
